- device-code-flow-console/MyInformation.cs
- device-code-flow-console/Program.cs
- device-code-flow-console/ProtectedApiCallHelper.cs
- device-code-flow-console/PublicAppUsingDeviceCodeFlow.cs
Refactoring of the sample to:
- enable better reusability
- highlight the code that does the magic.
- improve performance by reusing the HttpClient.
> Refactoring of the sample:

- README.md
MMicrosoft -> Microsoft
Fix typo in DeviceLogin URL listed.
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
N/A
* Test the code
N/A
Verify that the following are valid
N/A
> Fix type in devicelogin URL

- AppCreationScripts/AppCreationScripts.md
- AppCreationScripts/Cleanup.ps1
- AppCreationScripts/Configure.ps1
- AppCreationScripts/sample.json
- README.md
Improving the readme.md and Adding app creation scripts
Make the sample easier to configure (and automate)
`
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
[ x] Documentation content changes
```
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
```
* Test the code
Go through the README.md and try the automation
```
```
> Adding app creation scripts

- device-code-flow-console/device-code-flow-console.csproj
Update the sample to MSAL 2.7.1 (and .NET Core 2.2)
* ...
```
[ ] Yes
[ x] No
```
> update to MSAL 2.7.1

- device-code-flow-console/Program.cs
- device-code-flow-console/SampleConfiguration.cs
- device-code-flow-console/device-code-flow-console.csproj
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```
* Test the code
```
```
Verify that the following are valid
* ...
> Update to MSAL 3.0.3-preview

- device-code-flow-console/MyInformation.cs
- device-code-flow-console/ProtectedApiCallHelper.cs
- device-code-flow-console/device-code-flow-console.csproj
@bgavrilMS I tried doing 3.0.*, but it didn't pick up the latest version.
> update to 3.0.8

- device-code-flow-console/device-code-flow-console.csproj
> update to msal420

- README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```
* Test the code
```
```
Verify that the following are valid
* ...
> Removed preview text, updated YAML

- device-code-flow-console/device-code-flow-console.csproj
> Update to MSAL 4.6

- README.md
Removed the step: grant admin consent for the tenant. It is not required for this sample
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
> Removed grant admin consent step

- device-code-flow-console/device-code-flow-console.csproj
> Update to MSAL 480

- device-code-flow-console/device-code-flow-console.csproj
Update to MSAL.NET 4.20ay be needed here. -->
> Update to MSAL.NET 4.20

- device-code-flow-console/device-code-flow-console.csproj
> Update MSAL 4.32.0

- README.md
- device-code-flow-console/device-code-flow-console.csproj
> Update to MSAL 4.35 and minor readme changes

- device-code-flow-console/device-code-flow-console.csproj
Update to MSAL 4.38.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other: Sample update for new release
```
Get the code
> Update to MSAL 4.38.0

- device-code-flow-console/device-code-flow-console.csproj
update to msal 4.39.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other...update to msal 4.39.0
Get the code
> update to msal 4.39.0

- device-code-flow-console/device-code-flow-console.csproj
Updated to MSAL .Net 4.40
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Sample updates
> Updated to MSAL .Net 4.40

- device-code-flow-console/device-code-flow-console.csproj
Update to MSAL 4.42.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other... Update to MSAL 4.42.0
> Update to MSAL 4.42.0

- device-code-flow-console/device-code-flow-console.csproj
Update to MSAL 4.43.0
Update to MSAL 4.43.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update to MSAL 4.43.0
> Update to MSAL 4.43.0

- device-code-flow-console/device-code-flow-console.csproj
update to MSAL 4.44.0
[ ] Yes
[x ] No
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: update to MSAL 4.44.0
> update to MSAL 4.44.0

- device-code-flow-console/device-code-flow-console.csproj
Update to MSAL 4.45.0
No
Other... Please describe: Sample Update 
> Update to MSAL 4.45.0

- device-code-flow-console/device-code-flow-console.csproj
Update to MSAL 4.46.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: Update to MSAL 4.46.0
> Update to MSAL 4.46.0

- device-code-flow-console/device-code-flow-console.csproj
> Update to MSAL 4.47.0

- device-code-flow-console/device-code-flow-console.csproj
> Update to MSAL 4.49.0

- device-code-flow-console/device-code-flow-console.csproj
> Update to MSAL 4.49.1

- device-code-flow-console/device-code-flow-console.csproj
Update to MSAL 4.50.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: Update to MSAL 4.50.0
> Update to MSAL 4.50.0

- device-code-flow-console/MyInformation.cs
- device-code-flow-console/Program.cs
- device-code-flow-console/ProtectedApiCallHelper.cs
- device-code-flow-console/PublicAppUsingDeviceCodeFlow.cs
- device-code-flow-console/device-code-flow-console.csproj
> Update to MSAL 4.51.0

- device-code-flow-console/device-code-flow-console.csproj
> Update to MSAL 4.52.0
